%
(Header)
(Generated by gcodetools from Inkscape.)
(Using default header. To add your own header create file "header" in the output dir.)
M3
(Header end.)
G21 (All units in mm)

(Start cutting path id: rect2188)
(Change tool to Default tool)

G00 Z5.000000
G00 X0.242188 Y99.757812

G01 Z-0.500000 F100.0(Penetrate)
G01 X0.242188 Y0.242188 Z-0.500000 F400.000000
G01 X49.757812 Y0.242188 Z-0.500000
G01 X49.757812 Y99.757812 Z-0.500000
G01 X0.242188 Y99.757812 Z-0.500000
G00 Z5.000000

(End cutting path id: rect2188)


(Footer)
M5
G00 X0.0000 Y0.0000
%